In [7]:
# Introdução a Numpy
# Tópico 1 – Conhecendo o Array

import numpy as np

matriz1d = np.array([1, 2, 3])
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz1d * 2)
print(matriz1d + matriz1d)

print(matriz2d.shape)

print([1, 2, 3] + [4, 5, 6])
print(np.array([1, 2, 3]) + np.array([4, 5, 6]))

print([1, 2, 3] * 3)
print(np.array([1, 2, 3]) * 3)


[2 4 6]
[2 4 6]
(3, 3)
[1, 2, 3, 4, 5, 6]
[5 7 9]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [12]:
# Dimensões
# Formalmente, uma matriz é estritamente bidimensional. Na matemática, o termo correto para uma
# matriz de com dimensões acima de 2 é um tensor. 
# No entanto, no mundo da programação, é comum nos referirmos a matrizes multidimensionais.

import numpy as np

matriz1d = np.array([1, 2, 3])
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

print(matriz1d.ndim)
print(matriz2d.ndim)
print(matriz3d.ndim)
# print(matriz3d.shape)
# print(matriz1d.shape)


1
2
3


In [18]:
# Como em Matemática, as matrizes em NumPy realizam operações matemáticas básicas, como soma,
# subtração, multiplicação e multiplicação por número. Confira abaixo alguns exemplos das operações
# descritas anteriormente:

import numpy as np

matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2d2 = np.array([[20, 12, 10], [16, 55, 45], [33, 27, 18]])
print(matriz2d + matriz2d2)
print('\n')
print(matriz2d2 - matriz2d)
print('\n')
print(matriz2d * 2)

print('\n')
print(np.dot(matriz2d, matriz2d2))
print('\n')
print(np.dot(matriz2d2, matriz2d))
matriz23 = np.array([[1, 2, 3], [4, 5, 6]])
print('\n')
print(matriz23.shape)
print('\n')
print(np.dot(matriz23, matriz2d))
# print('\n')
# print(np.dot(matriz2d, matriz23))


[[21 14 13]
 [20 60 51]
 [40 35 27]]


[[19 10  7]
 [12 50 39]
 [26 19  9]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[151 203 154]
 [358 485 373]
 [565 767 592]]


[[138 180 222]
 [551 667 783]
 [267 345 423]]


(2, 3)


[[30 36 42]
 [66 81 96]]


In [21]:
# Algumas operações com matrizes

import numpy as np

ponto_original = np.array([3, 4])
rotacao = np.array([[-1.0, 0.0], [0.0, -1.0]])
ponto_rotacionado = np.dot(rotacao, ponto_original)
print(ponto_rotacionado)

translacao = np.array([5.0, 0.0])
ponto_transladado = translacao + ponto_original
print(ponto_transladado)

escala = 2
ponto_escalonado = escala * ponto_original
print(ponto_escalonado)


[-3. -4.]
[8. 4.]
[6 8]


In [30]:
# Confira um código com diversos exemplos para inicialização de matrizes utilizando métodos
# próprios da biblioteca.

import numpy as np

print(np.zeros((1, 3)))
print(np.ones((2, 2)))
print(np.full((1, 2), 3))
print(np.full((2, 1), np.nan))

# métodos arange e linspace
# As funções arange e linspace são bem parecidas, e você pode obter o mesmo resultado com as duas
# se desejar. Mas como escolher qual usar? De forma geral, pode-se usar arange com valores inteiros
# ou quando tiver um valor de passo específico. Já a linspace deve ser utilizada quando quiser incluir
# o valor final na sequência ou tiver um número fixo de elementos para produzir. 

print('\n')
print(np.arange(5))
print(np.arange(0, 2, 0.4))
print(np.linspace(0, 2, 6))


[[0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]]
[[nan]
 [nan]]


[0 1 2 3 4]
[0.  0.4 0.8 1.2 1.6]
[0.  0.4 0.8 1.2 1.6 2. ]


In [33]:
# Indexação
# A indexação nos Arrays do Numpy funciona de forma similar à indexação das listas. Na indexação de
# um array, é possível passar um índice específico, um intervalo sem passo ou um intervalo com passo.

import numpy as np

vetor = np.arange(10)
print(vetor[5])
print(vetor[5:])
print(vetor[:5])
print(vetor[2:8])
print(vetor[0:10:2])

# Com matrizes multidimensionais:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('\n')
print(matriz)
print(matriz[1, 1])
print(matriz[:, 1])
print(matriz[0, :])
print(matriz[:2, 1:])

# Pode parecer um pouco diferente, a princípio, trabalhar com várias dimensões, mas simplesmente
# pense nas operações de indexação agindo de forma independente em cada eixo.



5
[5 6 7 8 9]
[0 1 2 3 4]
[2 3 4 5 6 7]
[0 2 4 6 8]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[2 5 8]
[1 2 3]
[[2 3]
 [5 6]]


In [37]:
# A partir de um Array, é possível obter muitos outros arrays de diferentes shapes. Há duas funções
# principais para isso: ravel e reshape. A primeira retorna um vetor unidimensional com todos os
# valores, como se as dimensões tivessem sido “achatadas”. O método reshape recebe como argumento o
# novo shape, transforma a matriz original e cria uma nova com o tamanho especificado. É importante
# observar que o novo shape deve ser compatível com o shape original. Pois as matrizes devem possuir
# o mesmo número de elementos. Confira o código a seguir que ilustra casos de uso.

import numpy as np

matriz_coluna = np.array([[1, 2], [3, 4], [5, 6]])
print(matriz_coluna.shape)
vetor = matriz_coluna.ravel()
print(vetor)
matriz_linha = matriz_coluna.reshape((2, 3))
print(matriz_linha)
# matriz_invalida = matriz_coluna.reshape((2, 4))

(3, 2)
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
